# Google Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tradingview-kraken-webhook:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tradingview-kraken-webhook:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tradingview-kraken-webhook'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tradingview-kraken-webhook:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,LOG_LEVEL=INFO,GCP_PROJECT_ID=$PROJECT_ID'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/tradingview-kraken-webhook:$COMMIT_SHA'

# Substitution variables
substitutions:
  _REGION: us-central1  # Default region, can be overridden

# Timeout for the entire build
timeout: '1200s'